### ISSUE TITLE
Server Checklist

### ISSUE THREAD

**Issue by stdlibdoh** [oliverdhayden/PieR#1]
Adding it here so I don't have to keep jumping between repos.
Please add as you see fit.

**Comment by stdlibdoh** [comment]
- [x] Sketch architecture
- [x] MobileHub added
- [x] Add analytics
- [x] Log/Sign in
- [x] S3 bucket added
- [x] Data upload/storage
- [x] SageMaker instance added
- [x] Decide ML Algorithm to be used (Linear Leaner)
- [x] Script generated user data
- [x] Script generated ML data
- [x] Deploy ML Algorithm with test data
- [x] Analyse output and optimise algorithm
- [x] Generate personas based modifiers
- [x] Trigger reaction on upload, using Lambda Services
- [x] Feed output back to client

**Comment by stdlibdoh** [comment]
[Reserved for issues that might appear along the line]

- Current OAuth client ID is signed with generated-debug sha-1 fingerprint. This won't be allowed for publishing. See https://developer.android.com/studio/publish/app-signing.html#manage-key for fix.
- Currently, only upload is implemented. Download seems unnecessary and not sure about saving user profile data. Function isn't currently being used, need to add logic.
